import FooterSlot from "./components/FooterSlot";
import { SlotItem } from "./components/FooterSlot/schema";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const slots: SlotItem[] = [
    {
      name: "item",
      icon: "/images/home.svg",
      buttonName: "ホーム",
    },
    {
      name: "",
      icon: "/images/search.svg",
      buttonName: "さがす",
    },
    {
      name: "sell",
      icon: "/images/camera.svg",
      buttonName: "出品",
    },
    {
      name: "",
      icon: "/images/yen.svg",
      buttonName: "支払い",
    },
    {
      name: "",
      icon: "/images/bag.svg",
      buttonName: "はたらく",
    },
    {
      name: "",
      icon: "/images/person.svg",
      buttonName: "マイページ",
    },
  ];

  return (
    <html lang="en">
      <body>
        {children}
        <FooterSlot SlotItems={slots} />
      </body>
    </html>
  );
}
